### ISSUE TITLE
Question regarding communication between coordinators

### ISSUE THREAD

**Issue by zdurlan** [hsncr/ZinZinZin#1]
Hello! I really admire your work, and I have also commented on your Medium article.

I am a noob in Combine and I can’t make sense of the following: 

- I have a Config class (non-combine, non-coordinator) that has a function that starts a new coordinator class (Coordinator1) by setRoot. In Coordinator1 class, I have a VC that has a "dismiss" PassthroughSubject. Once I tap a button in this VC, I send through this dismiss publisher and then I listen in the Coordinator for the action using sink. This works great.
- After the above step, I want my Coordinator to send to the Config class the fact that the screen was dismissed. How can I do this? I tried using another PassthroughSubject in the Coordinator and make the Config class listen to it but they don't communicate. Any idea why?

In your demo you don't have communication between coordinators and non-coordinator classes, is this a limitation? 

Thanks in advance!

**Comment by hsncr** [comment]
Hi, I am linking your questions on Medium and my response as a reference; https://medium.com/@zdurlan.alin/amazing-work-fad49be50c80 

Also, I have some responses in the article that can be relevant. However, if you have any other issue or question, feel free to create another issue to ask.
